engines:
  structure:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  sonar-php:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- build/*
- cache/*
- test/*
- vendor/*
- sami_config.php